<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="woodpecker.local" name="hub.test.Login.UI" tests="2" failures="1" timestamp="22 Apr 2014 07:44:40 GMT" time="48.922" errors="0">
  <testcase name="testGUI" time="48.922" classname="hub.test.Login.UI"/>
  <testcase name="testFunctionality" time="0.000" classname="hub.test.Login.UI">
    <failure type="org.testng.TestNGException" message="
Method public void hub.test.Login.UI.testFunctionality(java.lang.Class,java.lang.String[]) throws java.lang.Exception requires a @DataProvider named : Data-Provider-Function">
      <![CDATA[org.testng.TestNGException: 
Method public void hub.test.Login.UI.testFunctionality(java.lang.Class,java.lang.String[]) throws java.lang.Exception requires a @DataProvider named : Data-Provider-Function
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testFunctionality -->
</testsuite> <!-- hub.test.Login.UI -->
